vich_uploader:
  db_driver: orm
  mappings:
    solicitation_attachments:
      uri_prefix: /uploads/attachments
      upload_destination: '%kernel.project_dir%/storage/attachments'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
